name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Use v4 for better file handling

      # Fix Permissions (Critical for Docker)
      - name: Fix Permissions
        run: |
          sudo chmod -R 777 .
          # Verify file exists before we even try to build
          ls -lh libffmpeg.so || echo "CRITICAL: libffmpeg.so IS MISSING!"

      - name: Build
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
